### ISSUE TITLE
Já está online?

### ISSUE THREAD

**Issue by alexandre-mbm** [jovemnerd/rede-social#2]
Onde?

**Comment by lpsouza** [comment]
@alexandre-mbm até onde sei este é o antigo projeto do **Jovem Nerd**, o **SkyNerd**! Este site vou descontinuado e o projeto dele, disponibilizado de forma open source! Então acredito que não tenha algum lugar ele online, mas tu pode *forkar* o projeto e colocar em seu ambiente interno para testes. :)

**Comment by alexandre-mbm** [comment]
@lpsouza, obrigado por sua atenção. Mas eu perguntei exatamente porque não quero ter esse trabalho. Esperava ver ao menos screenshot. Fazer deploy nem sempre sai baratinho.

**Comment by vinny** [comment]
@alexandre-mbm testar em localhost não dá trabalho algum. No <a href="https://www.google.com.br/search?q=SkyNerd&source=lnms&tbm=isch&sa=X&ei=eO79VIPzILaTsQS92YGAAQ&ved=0CAcQ_AUoAQ&biw=1366&bih=643">google</a> tem algumas imagens de como era o site.

**Comment by alexandre-mbm** [comment]
![Screenshot do SkyNerd](http://super.abril.com.br/blogs/superblog/files/2013/04/skynerd.jpg)

Não foram mais de 2 minutos para escolher a imagem acima como representativa. Enquanto que eu, não sendo desenvolvedor e não tendo prática de dia-a-dia com as tecnologias empregadas, gastaria provavelmente não menos do que 1 hora para executar o sistema em _localhost_.
