### ISSUE TITLE
Uma simples pergunta

### ISSUE THREAD

**Issue by IsaiasNascimentoCaetano** [jovemnerd/rede-social#3]
O projeto já está completo, ou ainda falta alguma coisa?

**Comment by vinny** [comment]
@IsaiasNascimentoCaetano acredito que este seja o projeto que operava no site do skynerd, é o mesmo codigo, ou seja é funcional.

**Comment by guicamillo** [comment]
@vinny @IsaiasNascimentoCaetano esse é exatamente o último build da skynerd que foi para o ar, portanto sim, é funcional.

**Comment by IsaiasNascimentoCaetano** [comment]
Obrigado.
